fix cicd

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -38,8 +38,19 @@ jobs:
     - name: Deploy Docker image to EC2
       run: |
         ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{vars.EC2_PUBLIC_API }} << 'EOF'
-        docker pull devmaksdev/react-nginx-app
-        docker stop $(docker ps -a -q) || true
-        docker rm $(docker ps -a -q) || true
-        docker run -d -p 80:80 --name react-app devmaksdev/react-nginx-app
+          # Update package index and install Docker if it's not already installed
+          if ! command -v docker &> /dev/null
+          then
+              echo "Docker not found, installing..."
+              sudo apt update
+              sudo apt install -y docker.io
+              sudo systemctl start docker
+              sudo systemctl enable docker
+              sudo usermod -aG docker $USER
+              newgrp docker
+          fi
+          docker pull devmaksdev/react-nginx-app
+          docker stop $(docker ps -a -q) || true
+          docker rm $(docker ps -a -q) || true
+          docker run -d -p 80:80 --name react-app devmaksdev/react-nginx-app
         EOF
